table DADOS_ATIVIDADE
	lineageTag: 7da8dbaa-a977-47af-b43e-ab3ea02d0624

	column Column1
		dataType: string
		lineageTag: 23cdbf60-0a67-4cd9-9424-7cf0aad57b90
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: d1a3d475-1120-48be-bc47-81af56f3bb74
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: string
		lineageTag: b1595f76-e449-4bcf-a6c3-bacd70241f06
		summarizeBy: none
		sourceColumn: Column3

		annotation SummarizationSetBy = Automatic

	column Column4
		dataType: string
		lineageTag: bac282f9-346c-477a-b46e-f68d46a2bb02
		summarizeBy: none
		sourceColumn: Column4

		annotation SummarizationSetBy = Automatic

	column Column5
		dataType: string
		lineageTag: d14a0603-33ba-4da8-9dc6-e4a89a2148e7
		summarizeBy: none
		sourceColumn: Column5

		annotation SummarizationSetBy = Automatic

	column Column6
		dataType: string
		lineageTag: ba9acc9d-9098-40d8-b8fd-8e1fce064611
		summarizeBy: none
		sourceColumn: Column6

		annotation SummarizationSetBy = Automatic

	column Column7
		dataType: string
		lineageTag: d76bca01-795d-4512-8a3b-e3477808d178
		summarizeBy: none
		sourceColumn: Column7

		annotation SummarizationSetBy = Automatic

	column Column8
		dataType: string
		lineageTag: ab766337-d509-4c41-a5df-ad8d26860af9
		summarizeBy: none
		sourceColumn: Column8

		annotation SummarizationSetBy = Automatic

	column Column9
		dataType: string
		lineageTag: 5f44ceb2-35be-4d6e-85db-bb0579406b90
		summarizeBy: none
		sourceColumn: Column9

		annotation SummarizationSetBy = Automatic

	column Column10
		dataType: string
		lineageTag: 159288e3-d106-4ee0-aa22-51d40d180d0b
		summarizeBy: none
		sourceColumn: Column10

		annotation SummarizationSetBy = Automatic

	column Column11
		dataType: string
		lineageTag: d491bfa7-397d-4f77-a34c-0fb9d99aad1a
		summarizeBy: none
		sourceColumn: Column11

		annotation SummarizationSetBy = Automatic

	column Column12
		dataType: string
		lineageTag: fd86db07-f9fb-4d21-beb4-c936fa6571d8
		summarizeBy: none
		sourceColumn: Column12

		annotation SummarizationSetBy = Automatic

	column Column13
		dataType: string
		lineageTag: 65c84ae7-ef5b-4398-bc3d-b33f5c5cb6bf
		summarizeBy: none
		sourceColumn: Column13

		annotation SummarizationSetBy = Automatic

	column Column14
		dataType: string
		lineageTag: 06ad0f5a-a271-420e-a210-d2c841e4e2bd
		summarizeBy: none
		sourceColumn: Column14

		annotation SummarizationSetBy = Automatic

	column Column15
		dataType: string
		lineageTag: 3dc30348-b184-4e31-8dbb-1b560490c2a1
		summarizeBy: none
		sourceColumn: Column15

		annotation SummarizationSetBy = Automatic

	column Column16
		dataType: string
		lineageTag: 0cfe46dd-a103-4198-92d6-66209cd10bff
		summarizeBy: none
		sourceColumn: Column16

		annotation SummarizationSetBy = Automatic

	column Column17
		dataType: string
		lineageTag: 6f57f2d0-afc3-47ae-83e9-31a2ee9a7104
		summarizeBy: none
		sourceColumn: Column17

		annotation SummarizationSetBy = Automatic

	column Column18
		dataType: string
		lineageTag: 5de750c7-1ffb-4eb0-9b9a-6be3d9b71165
		summarizeBy: none
		sourceColumn: Column18

		annotation SummarizationSetBy = Automatic

	column Column19
		dataType: string
		lineageTag: 1810dc65-44da-4f92-9e34-93e838e38ddc
		summarizeBy: none
		sourceColumn: Column19

		annotation SummarizationSetBy = Automatic

	column Column20
		dataType: string
		lineageTag: 66edc5bf-4905-4e9a-82f8-dd907043057e
		summarizeBy: none
		sourceColumn: Column20

		annotation SummarizationSetBy = Automatic

	column Column21
		dataType: string
		lineageTag: f9e37fa6-8055-4d03-b9e2-c1ae26385df2
		summarizeBy: none
		sourceColumn: Column21

		annotation SummarizationSetBy = Automatic

	column Column22
		dataType: string
		lineageTag: 65376cb6-9d47-4526-840a-a0fde2758ab7
		summarizeBy: none
		sourceColumn: Column22

		annotation SummarizationSetBy = Automatic

	column Column23
		dataType: string
		lineageTag: 8fc164bf-8fae-4f73-956f-f2dc30ab3374
		summarizeBy: none
		sourceColumn: Column23

		annotation SummarizationSetBy = Automatic

	column Column24
		dataType: string
		lineageTag: dc4965db-e90c-48d4-ae86-bd46d79afc0a
		summarizeBy: none
		sourceColumn: Column24

		annotation SummarizationSetBy = Automatic

	partition DADOS_ATIVIDADE = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\Isadora\Downloads\DADOS_ATIVIDADE.csv"),[Delimiter=",", Columns=24, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type text}, {"Column20", type text}, {"Column21", type text}, {"Column22", type text}, {"Column23", type text}, {"Column24", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

